- lib/createForm.js
When creating a new public service without using a concept as a template, we now prefill the `competentAuthority` and `executingAuthority` fields based on the logged in user that created the service instance.
> Prefill the "Authority" fields for blank service instances

- lib/retrieveForm.js
This allows us to use the same endpoint for fetching the conceptual public service forms.
> Add support for fetching form data for conceptual public services

- config.js
- lib/commonQueries.js
This makes it possible to show the listing items in the order they were created.
This PR complements the work done in https://github.com/lblod/ember-submission-form-fields/pull/120.
To test:
- link the ember-submission-form-fields branch into frontend-loket
- create a new (blank) concept
- create multiple listing items (for example "Kosten")
- save the form
- refresh the page
- check that the order is still the same as before (or check the response to see if it includes `sh:order` predicates
> Return the `sh:order` predicate for all listings when fetching form data

- lib/commonQueries.js
It seems I forgot this one in #26 so the websites were still displayed in the wrong order.
> Return `sh:order` for "OnlineProcedureRules"

- lib/createForm.js
It seems the fallback behavior was incorrect and produced an incorrect query which triggers an exception. We now use the same fallback as the regular form creating flow.
This fixes an issue where creating empty forms didn't work if the bestuurseenheid of the current user doesn't have a spatial.
DL-5050
> Fix the spatial fallback behavior for the empty forms

- app.js
- lib/retrieveForm.js
- lib/validateService.js
(Addresses DL-4913) Allows LPDC users to add different types of organizations (Gemeenten, OCMW, Autonoom Provinciebedrijf, Autonoom Gemeentebedrijf, etc.) in the "Uitvoerende Overheid" and "Bevoegde Overheid" fields.
To test:
* Add the below configuration to `docker-compose.override.yml` in your local `app-digitaal-loket` repo.
```
lpdc-management:
ports:
- 9229:9229
environment:
NODE_ENV: "development"
volumes:
- ./config/lpdc-management:/config
- ./data/files/lpdc:/data
- </path/to/>lpdc-management-service/:/app/
```
* Log in as any organization
* Go to the `Producten- en dienstencatalogus` module and add an existing/new service
* Go to the `Eigenschappen` tab of the service form and find the "Bevoegde overheid" and "Uitvoerende overheid" fields
* Searching in these fields should yield …
> Generate runtime concept schemes for all bestuurseenheden

- lib/retrieveForm.js
(Addresses DL-3983) Removes the English translation requirements when `YourEurope` is not chosen as the publication channel in the `Eigenschappen` tab in a LPDC form.
This is to be tested in tandem with the following PR for `app-digitaal-loket`: https://github.com/lblod/app-digitaal-loket/pull/400.
> Load the correct form based on the publication channel value

- lib/createForm.js
- lib/deleteForm.js
- lib/postProcessLdesConceptualService.js
Depends on https://github.com/lblod/app-digitaal-loket/pull/412 and https://github.com/lblod/frontend-loket/pull/290
TODO:
> Implement the concept label and filtering functionality

- lib/postProcessLdesConceptualService.js
When IPDC sends an archiving event over the LDES feed we now update the status of the concept to "archived". This allows us to hide the concept in the creation and link flows and makes it possible to show a message on the details page as well.
This still needs to be tested with the test LDES endpoint (https://github.com/lblod/app-ldes-endpoint)
> Add an "archived" status to concepts

- src/core/domain/bring-instance-up-to-date-with-concept-snapshot-version-domain-service.ts
**[LPDC-1255]**
The field from the concept is empty when the concept is meant for local authorities. This causes the form field to be empty after a merge, which is invalid and the instance cannot be sent without manual intervention.
**How to test correct workings**
Use a build with these changes in the stack (https://github.com/lblod/app-lpdc-digitaal-loket/tree/development). Observe an instance that has a new concept version. Make sure the instance is complete/valid (all required fields filled in). Use the "Wijzigingen overnemen" functionality, and "Concept volledig overnemen". Check afterwards that the "Bevoegde overheid" (and other required fields) are still filled in and that the instance can be sent in.
> Don't merge competent authorities from concept

- src/driven/persistence/bestuurseenheid-sparql-repository.ts
- src/driven/persistence/forms/eigenschappen/form.ttl
- test/driven/persistence/bestuurseenheid-repository.it-test.ts
- test/driven/persistence/bestuurseenheid-sparql-test-repository.ts
The NUTS LAU code list stored in the backend has been updated to the new 2024
scheme.
This updates
- the form query for the geographical scope field to use the new scheme
- the functionality to find administrative units by id (and its corresponding
tests)
This PR should be tested against https://github.com/lblod/app-lpdc-digitaal-loket/pull/34
LPDC-1261
> chore: use updated version of NUTS code list

- migration-scripts/transfer-instances/archive-instances-script.ts
- migration-scripts/transfer-instances/readme.md
- migration-scripts/transfer-instances/transfer-instance-service.ts
- migration-scripts/transfer-instances/transfer-instances-script.ts
- migration-scripts/transfer-instances/util.ts
This management service contains two scripts that simplify handling municipality mergers. These scripts generate migrations to
- copy product instances between two organisations; and
- archive product instances from an organisation.
The bulk of these scripts was prepared the previous team. This PR extends their work to fully cover all scenarios for the 2025 municipality mergers.
See the [README](https://github.com/lblod/lpdc-management-service/blob/feat/extend-instance-transfer-scripts/migration-scripts/transfer-instances/readme.md) on how to use the scripts.
Notes:
- the `archive-instances-script` will only be used some time in the future when the merged municipalities can be removed altogether, somewhere after 01/01/2025.
- the `transfer-instances-script` does **not** update the NUTS …
> Extend data migrations scripts

- src/core/domain/instance.ts
- test/core/domain/instance.unit-test.ts
Product instances that are labelled to be for municipality mergers:
- cannot be published to IPDC
- do not validate the addresses the user enters to allow them to enter new
address data without having to wait until the external address registry is
updated with respect to the municipality mergers.
Product instances that are labelled to be for municipality mergers:
- should be publishable to IPDC
- as we do not want to publish faulty data to IPDC, the address validation must
be enabled again for instances with the merger label
This PR removes the requirement that product instances must not be labelled for municipality mergers when publishing.
- should be assessed and deployed together with [frontend PR16](https://github.com/lblod/frontend-lpdc/pull/16)
- LPDC-1318
> feat: allow publishing product instances labelled for municipality mergers

- migration-scripts/transfer-instances/test/transfer-instances/transfer-instance.it-test.ts
- migration-scripts/transfer-instances/transfer-instance-service.ts
The transfer instance tests were not updated when the transfer instance was
modified in #47, consequently this resulted in false failures when running the
test suite.
This PR corrects the tests so they execute properly again, and remove some tests
that became irrelevant due to the changes the transfer instance logic.
> chore: cleaned up transfer instance tests

- app.ts
- config.ts
- src/core/application/validate-instance-for-publish-application-service.ts
- src/core/domain/bestuurseenheid.ts
- src/core/domain/spatial.ts
- src/core/port/driven/persistence/spatial-repository.ts
- src/driven/persistence/bestuurseenheid-sparql-repository.ts
- src/driven/persistence/form-definition-file-repository.ts
- src/driven/persistence/forms/eigenschappen/form.ttl
- src/driven/persistence/spatial-sparql-repository.ts
- test/core/application/validate-instance-for-publish-application-service.it-test.ts
- test/core/domain/bestuurseenheid-test-builder.ts
- test/core/domain/bestuurseenheid.unit-test.ts
- test/core/domain/instance-test-builder.ts
- test/core/domain/spatial-test-builder.ts
- test/core/domain/spatial.unit-test.ts
- test/data-integrity-validation/instance-publish-data-integrity.it-test.ts
- test/driven/persistence/bestuurseenheid-repository.it-test.ts
- test/driven/persistence/bestuurseenheid-sparql-test-repository.ts
- test/driven/persistence/spatial-repository.it-test.ts
- test/driven/persistence/spatial-sparql-test-repository.ts
Users should be shown an error message when they try to publish a product instance that has
- an inactive municipality as competent or executing authority
- an expired spatial as geographic scope.
The `ValidateInstanceForPublishApplicationService` already performs some validations on product instances before they can be published. This service is therefore extended with additional checks.
To enable checking for inactive organisations, it was opted to import the relevant status data from OrganisatiePortaal. This was done in a [PR](https://github.com/lblod/app-lpdc-digitaal-loket/pull/44) on the backend.
To be able the use this new status information, the `Bestuurseenheid` domain concept is extended with a new `status` property. Note that as not all organisations in LPDC actually have a …
> feat: do not allow publishing a product instance linked to old municipalities

- app.ts
- config.ts
- src/core/application/validate-instance-for-publish-application-service.ts
- src/core/domain/ensure-linked-authorities-exist-as-code-list-domain-service.ts
- src/core/domain/shared/iri.ts
- src/driven/persistence/code-sparql-repository.ts
- test/core/application/validate-instance-for-publish-application-service.it-test.ts
- test/core/domain/ensure-linked-authorities-exists-as-code-list-domain-service.it-test.ts
- test/core/domain/iri-test-builder.ts
- test/data-integrity-validation/instance-publish-data-integrity.it-test.ts
The validation for publishing product instances introduced in #50 is too strict with respect to competent and executing authorities. Specifically, product instances can have competent and/or executing authorities that are not administrative units. Instead these are resources of the type `skos:Concept` and have a URI of the form `https://data.vlaanderen.be/id/organisatie/OVOxxxxxx`.
The initial validation tries only to retrieve administrative unit resources for the specified authority URIs. This fails with a `NotFoundError` when a URI as above is specified, which in turn results in an incorrect error message being shown to the user.
This PR extends the validation logic to correctly deal with competent and executing authorities that are not administrative units. To this end the URIs a …
> fix: relax authority publish validation for product instances

- test/core/domain/bring-instance-up-to-date-with-concept-snapshot-version-domain-service.it-test.ts
The behaviour of the tested function was slightly changed in #45. Since then
competent authorities are only taken from the concept if the instance to update
does **not** have local as competent authority level. The test still assumed the
old behaviour in which competent authorities are always taken from the concept.
This fixes the test by correcting the `expectedInstance` to have the same
competent authorities of the updated instance. In the test at hand the competent
authorities of the instance are not changed during update since is has a local
competent authority level.
Fixing this issue makes the test suite more usable again and allows the jobs in
the woodpecker pipeline to succeed again.
> chore: fix failing test

- migration-scripts/transfer-instances/archive-instances-script.ts
Added the configuration to generate the needed product instance archival migrations for the 2025 municipality mergers. The intended archival is described in the related ticket. The following table (slightly modified from the ticket) summaries the intended result.
| Organisation name | Product instances to archive |
|-------------------|------------------------------|
| Antwerpen         | None                         |
| Borsbeek          | All                          |
|                   |                              |
| Beveren           | All                          |
| Kruibeke          | All                          |
| Zwijndrecht       | All                          |
|                   |                              |
| Bilzen-Hoeselt    | Non-merger instances         |
| …
> feat: product instance archival for municipality mergers 2025

- app.ts
- src/core/domain/bestuurseenheid.ts
- src/core/domain/ensure-linked-authorities-exist-as-code-list-domain-service.ts
- src/core/domain/instance-snapshot-to-instance-merger-domain-service.ts
- src/core/domain/shared/iri.ts
- src/core/domain/shared/lpdc-error.ts
- src/core/port/driven/persistence/bestuurseenheid-repository.ts
- src/driven/persistence/bestuurseenheid-sparql-repository.ts
- src/driven/persistence/code-sparql-repository.ts
- test/core/application/instance-snapshot-processor-application-service.it-test.ts
- test/core/domain/ensure-linked-authorities-exists-as-code-list-domain-service.it-test.ts
- test/core/domain/instance-snapshot-test-builder.ts
- test/core/domain/instance-snapshot-to-instance-merger-domain-service.it-test.ts
- test/core/domain/shared/iri.unit-test.ts
- test/driven/external/bestuurseenheid-registration-code-through-subject-page-or-api-fetcher.it-test.ts
- test/driven/persistence/bestuurseenheid-repository.it-test.ts
- test/driven/persistence/instance-snapshot-repository.it-test.ts
More external entities are starting to integrate with LPDC by sending product instance snapshots via LDES. We want to ensure a certain level of data quality of the received snapshots before processing them and sending them to IPDC.
Validate any received snapshots as part of processing them upon arrival at LPDC. Only snapshots that pass all validations will be converted to an actual product instance. More specifically, we add validations for the URIs linking a snapshot to other resources.
- The administrative unit that created the snapshot must exist in LPDC and may not have the status inactive.
- If a snapshot is linked to a concept, this concept must be an existing concept in LPDC.
- As geographical area(s), a snapshot may only link to existing and not expired spatials.
- For the linked …
> feat: additional validations for URIs contained in product instance snapshots

- src/driven/persistence/form-definition-file-repository.ts
As part of the NUTS/LAU code list update its concept scheme URI was extracted to
a constant to avoid it being specified in multiple places (see #46 and
#50). This required putting a placeholder string in the characteristics form
file, which is overwritten with the actual value when the form file is loaded.
For concept forms the step to overwrite the place holder was not added resulting
in a form that is loaded with the placeholder string stil in it. Since concept
forms are not editable in LPDC this currently does not lead to any issues. This
commit does add the replacement for the placeholder string such that a correct
form is always sent to the frontend. This makes it consistent with other
placeholders that are already replaced and prevents (subtle) bugs should the
concept forms ever …
> fix: replace NUTS URI placeholder in concept characteristics form

- src/core/domain/session.ts
- src/driving/sessions.ts
When using impersonation in LPDC, allow the LoketLB-admin role to see data.
Logging in as an admin into LPDC, we need to be able to load data as to not crash the application, so that impersonation can be started.
> Add Loket-admin as a role

- test/core/application/validate-instance-for-publish-application-service.it-test.ts
- test/core/domain/instance-test-builder.ts
- test/data-integrity-validation/instance-publish-data-integrity.it-test.ts
- test/driven/persistence/authority-level-sparql-test-repository.ts
- test/driven/persistence/instance-repository.it-test.ts
Due to the changes in #63 these tests were broken as the tested services could no longer be correctly instantiated. This PR adds the missing argument such that the existing tests correctly run again.
> fix: tests for the validations of product instances to be published

- .prettierrc
- src/core/domain/address.ts
- src/core/domain/contact-point.ts
- src/core/domain/instance.ts
- src/core/domain/language-string.ts
- test/core/domain/instance.unit-test.ts
LPDC-1402
Filter out empty contactpoints / addresses before creating. Since these objects don't have *any* required fields they end up getting created as empty objects and pollute the ui/data.
Run in the lpdc stack, create a new instance. Multiple scenarios:
- empty contactpoint -> should not be visible after saving
- empty contactpoint with empty address -> should not be visible after saving
- filled in contactpoint with empty address -> contactpoint should be visible, address should be cleaned up
- filled in conctactpoint with filled in address -> contactpoint and address should remain visible
> [LPDC-1402]: filter out empty contactpoints
